#ifndef CONFIG_H
#define CONFIG_H

#define MAPBASE_TILE_WIDTH 32L
#define MAPBASE_TILE_HEIGHT 32L
#define MAPBASE_TILE_COUNT MAPBASE_TILE_WIDTH * MAPBASE_TILE_HEIGHT
#define MAPBASE_SIZE MAPBASE_TILE_COUNT*2L

// Our default Tile and Map Base addresses
#define L0_MAPBASE_ADDR 0x00000L
#define L1_MAPBASE_ADDR L0_MAPBASE_ADDR + MAPBASE_SIZE
#define TILEBASE_ADDR L1_MAPBASE_ADDR + MAPBASE_SIZE

#define PALETTE_ADDR 0x1FA00L

#define MAP_BANK 1

void init();

#endif