#ifndef CONFIG_H
#define CONFIG_H

#define L0_TILE_SIZE 256L
#define L1_TILE_SIZE 64L

#define L0_MAPBASE_TILE_WIDTH 32L
#define L0_MAPBASE_TILE_HEIGHT 32L
#define L1_MAPBASE_TILE_WIDTH 64L
#define L1_MAPBASE_TILE_HEIGHT 32L

#define L0_MAPBASE_TILE_COUNT L0_MAPBASE_TILE_WIDTH * L0_MAPBASE_TILE_HEIGHT
#define L0_MAPBASE_SIZE L0_MAPBASE_TILE_COUNT*2L
#define L1_MAPBASE_TILE_COUNT L1_MAPBASE_TILE_WIDTH * L1_MAPBASE_TILE_HEIGHT
#define L1_MAPBASE_SIZE L1_MAPBASE_TILE_COUNT*2L

#define L0_TILE_COUNT_DNG 32
#define L0_TILE_COUNT_GAME 104
#define L1_TILE_COUNT 256

#define L0_TILEBASE_DNG_SIZE L0_TILE_COUNT_DNG * L0_TILE_SIZE
#define L0_TILEBASE_GAME_SIZE L0_TILE_COUNT_GAME * L0_TILE_SIZE
#define L1_TILEBASE_SIZE L1_TILE_COUNT * L1_TILE_SIZE

// Our default Tile and Map Base addresses
#define L0_MAPBASE_ADDR 0x00000L
#define L1_MAPBASE_ADDR L0_MAPBASE_ADDR + L0_MAPBASE_SIZE
#define L0_TILEBASE_DNG_ADDR L1_MAPBASE_ADDR + L1_MAPBASE_SIZE
#define L0_TILEBASE_ADDR L0_TILEBASE_DNG_ADDR // Starting L0 Tilebase Address
#define L0_TILEBASE_GAME_ADDR L0_TILEBASE_DNG_ADDR + L0_TILEBASE_DNG_SIZE
#define L1_TILEBASE_ADDR L0_TILEBASE_GAME_ADDR + L0_TILEBASE_GAME_SIZE

#define L1_OVERLAY_X 30

#define PALETTE_ADDR 0x1FA00L

#define MAP_BANK 1
#define INSTRUCTIONS_BANK 2
#define CONFIG_BANK 3
#define PLAYER_BANK 4

void loadBankedCode();
void init();
void initTiles();

#endif