#ifndef CONFIG_H
#define CONFIG_H

#define L0_TILE_SIZE 256L
#define L1_TILE_SIZE 64L

#define L0_MAPBASE_TILE_WIDTH 32L
#define L0_MAPBASE_TILE_HEIGHT 32L
#define L1_MAPBASE_TILE_WIDTH 64L
#define L1_MAPBASE_TILE_HEIGHT 32L

#define L0_MAPBASE_TILE_COUNT L0_MAPBASE_TILE_WIDTH * L0_MAPBASE_TILE_HEIGHT
#define L0_MAPBASE_SIZE L0_MAPBASE_TILE_COUNT*2L
#define L1_MAPBASE_TILE_COUNT L1_MAPBASE_TILE_WIDTH * L1_MAPBASE_TILE_HEIGHT
#define L1_MAPBASE_SIZE L1_MAPBASE_TILE_COUNT*2L

#define L0_TILE_COUNT_DNG 32
#define L0_TILE_COUNT_GAME 112
#define L1_TILE_COUNT 256

#define L0_TILEBASE_DNG_SIZE L0_TILE_COUNT_DNG * L0_TILE_SIZE
#define L0_TILEBASE_GAME_SIZE L0_TILE_COUNT_GAME * L0_TILE_SIZE
#define L1_TILEBASE_SIZE L1_TILE_COUNT * L1_TILE_SIZE

// Our default Tile and Map Base addresses
#define L0_MAPBASE_ADDR 0x00000L
#define L1_MAPBASE_ADDR L0_MAPBASE_ADDR + L0_MAPBASE_SIZE
#define L0_TILEBASE_DNG_ADDR L1_MAPBASE_ADDR + L1_MAPBASE_SIZE
#define L0_TILEBASE_ADDR L0_TILEBASE_DNG_ADDR // Starting L0 Tilebase Address
#define L0_TILEBASE_GAME_ADDR L0_TILEBASE_DNG_ADDR + L0_TILEBASE_DNG_SIZE
#define L1_TILEBASE_ADDR L0_TILEBASE_GAME_ADDR + L0_TILEBASE_GAME_SIZE

#define L1_OVERLAY_X 30

#define PALETTE_ADDR 0x1FA00L

// sizeof(Entity) = 53 - check this after changes
// entityList size = 75 Entities * 53 = 3975
// mapStatus = 32*32 = 1024
// mapbank code = 2582 (we allow for 3072)
// total = 7581 (still less than 8192 so we are good!)

#define MAP_BANK_CODE_SIZE 3072 // Leave room for code in Bank 1
#define MAP_STATUS_ADDR (0xA000 + MAP_BANK_CODE_SIZE) // There is some code at beginning of the bank
#define MAP_STATUS_SIZE 1024

#define ENTITY_LIST_ADDR (MAP_STATUS_ADDR + MAP_STATUS_SIZE) // Put after mapStatus

#define MAP_BANK 1
#define CODE_BANK 2
#define STRING_BANK 3

#define ZSM_BANK 10
#define SFX_BANK_1 11

#define MUSIC_BANK_TITLE 12 

#define MUSIC_BANK_WELCOME 13
#define MUSIC_WELCOME_SIZE 3

#define MUSIC_BANK_KEYS MUSIC_BANK_WELCOME + MUSIC_WELCOME_SIZE
#define MUSIC_KEYS_SIZE 6

#define MUSIC_BANK_TREASURE MUSIC_BANK_KEYS + MUSIC_KEYS_SIZE
#define MUSIC_TREASURE_SIZE 6

#define MUSIC_BANK_SCROLLS MUSIC_BANK_TREASURE + MUSIC_TREASURE_SIZE
#define MUSIC_SCROLLS_SIZE 6

#define MUSIC_BANK_FOOD MUSIC_BANK_SCROLLS + MUSIC_SCROLLS_SIZE
#define MUSIC_FOOD_SIZE 4

#define MUSIC_BANK_NIGH MUSIC_BANK_FOOD + MUSIC_FOOD_SIZE
#define MUSIC_NIGH_SIZE 3

#define MUSIC_BANK_LAUGH MUSIC_BANK_NIGH + MUSIC_NIGH_SIZE
#define MUSIC_LAUGH_SIZE 5

#define MUSIC_BANK_START MUSIC_BANK_LAUGH + MUSIC_LAUGH_SIZE

void toggleLayers(unsigned char show);
void showTitle();
void loadBankedCode();
void init();
void initTiles();
void spritesConfig();

#endif